//  Smart Keypad Advanced.cpp
/*
Given a long vector of strings, print the strings that contain the strings generated by numeric string str.

string searchIn [] = {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };
For example, if the input is 26 and the string is coding, then output should be coding since 26 can produce co which is contained in coding.


*/
#include <iostream>
#include <vector>
#include <string>
using namespace std;
vector <string> searchIn= {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };
vector <string> phone = { " ", " ", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz" };

bool find (string &a, string &b)
{
    for (int i=0; i<(b.size()-a.size()+1); i++)
    {
        if (b.substr(i, a.size())==a) return true;
    }
    return false;
}

void help (string &t, vector <string> &searchIn)
{
    for (int i=0; i<searchIn.size(); i++)
    {
        if (find(t, searchIn[i])) {
            cout << searchIn[i]<<endl;
        }
    }
}

void check (string &s, int index, string t)
{
    if (index==s.size()) {
        help (t, searchIn);
    } else {
        int d = s[index] - '0';
        string w = phone[d];
        for (int i=0; i<w.size(); i++)
        {
            t.push_back(w[i]);
            ++index;
            check(s, index, t);
            --index;
            t.pop_back();
        }
    }
}

int main ()
{
    string s, t;
    cin >> s;

    check (s, 0, t);

    return 0;
}
